@startuml

left to right direction

actor Utente
actor "Brent API" as API

rectangle BrentWatch {

usecase "Registrazione" as UC1
usecase "Login" as UC2
usecase "Visualizzare prezzo Brent" as UC3
usecase "Consultare storico prezzi" as UC4
usecase "Creare alert" as UC5
usecase "Gestire alert" as UC6
usecase "Aggiornare prezzo" as UC7

}

Utente --> UC1
Utente --> UC2
Utente --> UC3
Utente --> UC4
Utente --> UC5
Utente --> UC6

API --> UC7

@enduml